package me.datatags.commandminerewards.commands;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.bukkit.command.CommandSender;

public abstract class CompoundCommand extends CMRCommand {
	private List<CompoundCommand> children = new ArrayList<>();
	@Override
	public String getExtensiveDescription() {
		return null; // auto-generated by tab-completer for compound commands
	}
	@Override
	public String getUsage() {
		return null; // also auto-generated
	}
	// we don't specify getArgs() specially here because they're auto-generated as well
	@Override
	public boolean onCommand(CommandSender sender, String[] args) {
		return false; // so they see the usage information. If this command is used with an argument, the dispatcher should pass it to the subcommand
	}
	public List<CompoundCommand> getChildren() {
		return children;
	}
	protected void registerChildren(CompoundCommand... cc) {
		children.addAll(Arrays.asList(cc));
	}
	@Override
	public String[] getExamples() {
		return new String[] {}; // compound commands don't need examples
	}
	@Override
	public abstract void init();
}
